# Contingency Table Analysis
Download the datafile adult.data from the UCI Machine Learning Repository. This is a selection of the Census data from 1994, and it has 48842 instances over 14 categorial, real and integer attributes.

Compute the contingency matrix for variables education and race, and compute the $\chi^2$ statistic using your own function, i.e., write a function that takes as input two categorical column-vectors, and returns the $\chi^2$ value and its p-value. At the 99% confidence level, are education and race dependent?

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
df = pd.read_csv('/content/adult.data', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
df = df.drop(['income'], axis=1)
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

In [4]:
df.nunique()

age                  73
workclass             9
fnlwgt            21648
education            16
education-num        16
marital-status        7
occupation           15
relationship          6
race                  5
sex                   2
capital-gain        119
capital-loss         92
hours-per-week       94
native-country       42
dtype: int64

In [5]:
def table_analysis(cat1=df['education'], cat2=df['race']):
  contingency_table = pd.crosstab(cat1, cat2)
  chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

  return chi2, p

In [6]:
chi2, p = table_analysis()
print(chi2)
print(p)

730.6712962254584
5.547319569858433e-116

In [7]:
cats = ['workclass',
        'education',
        'marital-status',
        'occupation',
        'relationship',
        'race',
        'sex',
        'native-country']

for cat1 in cats:
  for cat2 in cats:
    if cat1 != cat2:
      chi2, p = table_analysis(df[cat1], df[cat2])
      print(f'{cat1}     {cat2}     {chi2}     {p}')

workclass     education     2572.1048319192323     0.0
workclass     marital-status     1413.5586972450485     1.531121642660398e-264
workclass     occupation     41676.64797359809     0.0
workclass     relationship     1586.3718429370779     3.445700331287451e-307
workclass     race     412.53659238316556     1.1256884540047491e-67
workclass     sex     768.9139234794314     1.0286039850311005e-160
workclass     native-country     546.6416205335809     3.6510642780637936e-13
education     workclass     2572.1048319192328     0.0
education     marital-status     1638.1373573227854     1.1706731158022685e-282
education     occupation     15997.777225542155     0.0
education     relationship     2449.2301947700535     0.0
education     race     730.6712962254584     5.547319569858433e-116
education     sex     297.71500372503687     1.667778440920507e-54
education     native-country     8592.458433297219     0.0
marital-status     workclass     1413.5586972450483     1.5311216426603977e-264
marital-status     education     1638.1373573227856     1.1706731158022683e-282
marital-status     occupation     3466.8872612903847     0.0
marital-status     relationship     38765.198041121424     0.0
marital-status     race     923.8086971524608     1.3087338193819433e-179
marital-status     sex     6944.747255715985     0.0
marital-status     native-country     1043.1135058773248     1.325642820456137e-98
occupation     workclass     41676.64797359809     0.0
occupation     education     15997.777225542155     0.0
occupation     marital-status     3466.8872612903847     0.0
occupation     relationship     5194.643196156871     0.0
occupation     race     850.8664424960739     1.6090405792152354e-142
occupation     sex     5863.7547861768935     0.0
occupation     native-country     2437.2965238719535     3.056006193732551e-227
relationship     workclass     1586.371842937078     3.4457003312866674e-307
relationship     education     2449.2301947700535     0.0
relationship     marital-status     38765.19804112144     0.0
relationship     occupation     5194.6431961568705     0.0
relationship     race     1253.3840595964268     2.825570052626311e-253
relationship     sex     13714.73999416357     0.0
relationship     native-country     1184.8638107974953     1.7228064998719162e-137
race     workclass     412.53659238316556     1.1256884540047491e-67
race     education     730.6712962254585     5.547319569858429e-116
race     marital-status     923.8086971524608     1.3087338193819433e-179
race     occupation     850.8664424960739     1.6090405792152354e-142
race     relationship     1253.3840595964264     2.825570052626954e-253
race     sex     454.2671089131088     5.192061302760456e-97
race     native-country     21814.79324434658     0.0
sex     workclass     768.9139234794313     1.0286039850311591e-160
sex     education     297.71500372503687     1.667778440920507e-54
sex     marital-status     6944.747255715985     0.0
sex     occupation     5863.7547861768935     0.0
sex     relationship     13714.739994163572     0.0
sex     race     454.2671089131088     5.192061302760456e-97
sex     native-country     146.81173973490073     7.950883043096852e-14
native-country     workclass     546.6416205335809     3.6510642780637936e-13
native-country     education     8592.458433297219     0.0
native-country     marital-status     1043.1135058773248     1.325642820456137e-98
native-country     occupation     2437.2965238719535     3.056006193732551e-227
native-country     relationship     1184.863810797495     1.722806499871917e-137
native-country     race     21814.793244346576     0.0
native-country     sex     146.81173973490073     7.950883043096852e-14

In [8]:
# p ~ 0 < alpha = 0.01 -> dependent